In [111]:
import pandas as pd

In [112]:
df = pd.read_csv('retail_sales_dataset.csv')

In [113]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [114]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [115]:
df.shape

(1000, 9)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

1 - Handling Missing Vlaues

In [117]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [118]:
df.dropna(inplace=True)

2 - Handling Duplicates

In [119]:
df.duplicated().value_counts()

False    1000
Name: count, dtype: int64

In [120]:
df.drop_duplicates(inplace=True)

3 - Handle Data Types

In [121]:
df['Price per Unit'] = df['Price per Unit'].astype(float)
df['Date'] = pd.to_datetime(df['Date'])

4 - Handle Columns Names

In [122]:
for x, y in zip(df.columns, df.columns) :
    if x == 'Price per Unit' :
        x = 'unit price'
        x = x.replace(' ', '_').lower()
        df.rename(columns={y:x}, inplace=True)
    elif x == 'Total Amount' :
        x = 'revenue'
        x = x.replace(' ', '_').lower()
        df.rename(columns={y:x}, inplace=True)
    else :
        x = x.replace(' ', '_').lower()
        df.rename(columns={y:x}, inplace=True)

5 - Data Standardization

In [123]:
# In gender Column we will replcae 'Male/Female' by 'M/F'
df['gender'] = df['gender'].str.strip().str.lower().apply(lambda p: 'M' if  p == 'male' else 'F')
# In product_category Column we will use lower_case
df['product_category'] = df['product_category'].str.lower()

6 - Validating Consistency

In [124]:
# Excepection is 0
list_of_mistakes = []
for x,y, z in zip(df['quantity'], df['unit_price'], df['revenue']):
    if (x * y) != z :
        list_of_mistakes.append(1)
sum(list_of_mistakes)

0

Export to Excel File

In [125]:
df.to_excel('retial_sales.xlsx', index=False)

Export to Csv File

In [126]:
df.to_csv('retail_sales.csv', index=False)